/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
export const OidcModuleNgFactory:i0.NgModuleFactory<i1.OidcModule> = i0.ɵcmf(i1.OidcModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.OidcModule,i1.OidcModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL29wdC9oYXdhaWkvd29ya3NwYWNlL2hhd2FpaS1wYWNrYWdlcy9wYWNrYWdlcy9uZ3gtb2lkYy1pbXBsaWNpdC9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9vcHQvaGF3YWlpL3dvcmtzcGFjZS9oYXdhaWktcGFja2FnZXMvcGFja2FnZXMvbmd4LW9pZGMtaW1wbGljaXQvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzsifQ==
